### PR TITLE
Fix binstub

### LINKED ISSUE #35: You checked in the bundler binstub of bin/uuid
`bin/uuid` is bundler binstub and cannot be executed.

<pre>
$ uuid
/home/hal/.gem/ruby/1.9.3/gems/bundler-1.3.5/lib/bundler/rubygems_integration.rb:280:in `block in replace_bin_path': can't find executable uuid (Gem::Exception)
	from /home/hal/.gem/ruby/1.9.3/gems/uuid-2.3.7/bin/uuid:16:in `<top (required)>'
	from /home/hal/.gem/ruby/1.9.3/bin/uuid:19:in `load'
	from /home/hal/.gem/ruby/1.9.3/bin/uuid:19:in `<main>'
</pre>

### PR DESCRIPTION
**Pull request by jhass**
Closes #35

I also included a commit to update the Gemfile & Gemfile.lock

### CODE REVIEW

**Comment by postmodern** [comment]
@assaf Ping? Looks good to merge.

**Comment by assaf** [comment]
I don't have a Ruby setup. @drbrain you able to make a release?

**Comment by drbrain** [comment]
Released 2.3.8

**Comment by assaf** [comment]
@drbrain thanks for cutting the release!

**Comment by twk3** [comment]
This change didn't appear to make it into the 2.3.8 gem

**Pull request merged**
